### ISSUE TITLE
Unable to stop transcription on 0.4.0

### ISSUE THREAD

**Issue by EightPool** [mybigday/whisper.rn#183]
I was testing the latest RC version and noticed that the stop method is broken on iOS since [0.4.0-rc.5](https://github.com/mybigday/whisper.rn/releases/tag/v0.4.0-rc.5). Also, it appears that the stop method issue on Android has not been resolved with [#143](https://github.com/mybigday/whisper.rn/pull/143). 

Is there a new method to abort the transcription of a file instead of using stop() ?

**Comment by jhen0409** [comment]
Fixed in 1421c55 and d1541ae.

**Comment by sdip15fa** [comment]
Hello, after trying v4.0.0-rc.7, it appears that transcription still cannot be stopped.

**Comment by jhen0409** [comment]
Due to recent whisper.cpp changes, the abort callback is not used in ggml_graph_compute_helper anymore. The abort_callback only used in whisper_encode_internal / whisper_decode_internal now, 

I'll look at the reasons for this change later.

**Comment by jobpaardekooper** [comment]
@jhen0409 Do you have any update on this? Just tried out the newest RC and having the gpu optional available is incredibly great. Sadly this issue is a real blocker for a full 4.0 release.

Any help needed from the community? If so it would be nice to have a few extra pointers on this.

Thanks for all the work on this great library.
